-- Criação da tabela de movimentações financeiras
-- Seguindo o padrão do projeto: nomes em maiúsculas, colunas em maiúsculas com underscore

CREATE TABLE IF NOT EXISTS MOVIMENTACAO_FINANCEIRA (
    ID SERIAL PRIMARY KEY,
    TIPO_MOVIMENTACAO VARCHAR(20) NOT NULL CHECK (TIPO_MOVIMENTACAO IN ('ENTRADA', 'SAIDA')),
    TIPO_CONTA VARCHAR(20) NOT NULL CHECK (TIPO_CONTA IN ('CONTA_DIGITAL', 'DINHEIRO_FISICO')),
    CATEGORIA VARCHAR(20) NOT NULL CHECK (CATEGORIA IN ('VENDA', 'COMPRA', 'DOACAO', 'SALARIO', 'ALUGUEL', 'SERVICOS', 'IMPOSTOS', 'MATERIAL_ESCRITORIO', 'EVENTOS', 'OUTROS')),
    DESCRICAO VARCHAR(500) NOT NULL,
    VALOR NUMERIC(19,2) NOT NULL CHECK (VALOR > 0),
    DATA_MOVIMENTACAO DATE NOT NULL,
    STATUS VARCHAR(20) NOT NULL CHECK (STATUS IN ('CONFIRMADA', 'PENDENTE', 'CANCELADA')),
    OBSERVACAO VARCHAR(1000),
    DATA_CRIACAO DATE NOT NULL DEFAULT CURRENT_DATE,
    DATA_ATUALIZACAO DATE
);

-- Índices para performance nas consultas mais comuns
CREATE INDEX IF NOT EXISTS IDX_MOVIMENTACAO_DATA ON MOVIMENTACAO_FINANCEIRA(DATA_MOVIMENTACAO);
CREATE INDEX IF NOT EXISTS IDX_MOVIMENTACAO_TIPO ON MOVIMENTACAO_FINANCEIRA(TIPO_MOVIMENTACAO);
CREATE INDEX IF NOT EXISTS IDX_MOVIMENTACAO_TIPO_CONTA ON MOVIMENTACAO_FINANCEIRA(TIPO_CONTA);
CREATE INDEX IF NOT EXISTS IDX_MOVIMENTACAO_STATUS ON MOVIMENTACAO_FINANCEIRA(STATUS);
CREATE INDEX IF NOT EXISTS IDX_MOVIMENTACAO_CATEGORIA ON MOVIMENTACAO_FINANCEIRA(CATEGORIA);

-- Índices compostos para relatórios mais otimizados
CREATE INDEX IF NOT EXISTS IDX_MOVIMENTACAO_TIPO_DATA ON MOVIMENTACAO_FINANCEIRA(TIPO_MOVIMENTACAO, DATA_MOVIMENTACAO);
CREATE INDEX IF NOT EXISTS IDX_MOVIMENTACAO_CONTA_STATUS ON MOVIMENTACAO_FINANCEIRA(TIPO_CONTA, STATUS);
CREATE INDEX IF NOT EXISTS IDX_MOVIMENTACAO_STATUS_DATA ON MOVIMENTACAO_FINANCEIRA(STATUS, DATA_MOVIMENTACAO);

-- Comentários sobre a tabela e colunas importantes
COMMENT ON TABLE MOVIMENTACAO_FINANCEIRA IS 'Tabela principal para controle de movimentações financeiras (entradas e saídas)';
COMMENT ON COLUMN MOVIMENTACAO_FINANCEIRA.TIPO_MOVIMENTACAO IS 'Tipo da movimentação: ENTRADA ou SAIDA';
COMMENT ON COLUMN MOVIMENTACAO_FINANCEIRA.TIPO_CONTA IS 'Onde o dinheiro está: CONTA_DIGITAL ou DINHEIRO_FISICO';
COMMENT ON COLUMN MOVIMENTACAO_FINANCEIRA.CATEGORIA IS 'Categoria da movimentação para agrupamento em relatórios';
COMMENT ON COLUMN MOVIMENTACAO_FINANCEIRA.VALOR IS 'Valor da movimentação em reais, sempre positivo';
COMMENT ON COLUMN MOVIMENTACAO_FINANCEIRA.STATUS IS 'Situação atual: CONFIRMADA (entra no saldo), PENDENTE ou CANCELADA';
COMMENT ON COLUMN MOVIMENTACAO_FINANCEIRA.DATA_CRIACAO IS 'Data de criação do registro';
COMMENT ON COLUMN MOVIMENTACAO_FINANCEIRA.DATA_ATUALIZACAO IS 'Data da última atualização do registro';
